TRUNCATE TABLE `comment`;

ALTER TABLE user
ADD COLUMN `follow` BIGINT NOT NULL COMMENT '用户关注数量',
ADD COLUMN `fans` BIGINT NOT NULL COMMENT '用户粉丝数量',
ADD COLUMN `allpost_like` BIGINT NOT NULL COMMENT '用户点赞数量';


ALTER TABLE `post` 
ADD COLUMN `community_id` BIGINT NOT NULL DEFAULT 1 COMMENT '社区id';