INSERT INTO `user` (
    `username`, 
    `password_hash`, 
    `email`, 
    `phone`, 
    `nickname`, 
    `avatar_path`, 
    `self_evaluated_level`, 
    `system_score`, 
    `personality_tags`, 
    `play_style_tags`, 
    `preferred_skill_level`, 
    `preferred_time_slots`, 
    `preferred_regions`, 
    `max_cost`, 
    `historical_partners`, 
    `ratings_given`
) VALUES (
    '2022210826', 
    '$2a$10$hashedpassword', 
    'xiaoen@example.com', 
    '15555555555', 
    '小奀', 
    'avatars/custom123.jpg', 
    'advanced', 
    85, 
    '{"competitive": true, "punctual": true, "friendly": true}', 
    '{"baseline": true, "serve_volley": false}', 
    'intermediate', 
    '{"weekday_evenings": true, "weekends": true}', 
    '["朝阳区", "海淀区"]', 
    200, 
    '[101, 205, 307]', 
    '{"205": 4.5, "307": 3.8}'
);