// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API支持",
            "email": "1076763695@qq.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "使用用户名密码登录系统",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证服务"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录凭证",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码，最少6位\nRequired: true\nExample: password123",
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "description": "用户名，4-20位字母数字组合\nRequired: true\nExample: admin123",
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 4
                }
            }
        },
        "model.LoginResp": {
            "type": "object",
            "properties": {
                "avatar_path": {
                    "description": "头像路径\nExample: /avatars/default.png",
                    "type": "string"
                },
                "createTime": {
                    "description": "创建时间\nExample: 2023-01-01 12:00:00",
                    "type": "string"
                },
                "email": {
                    "description": "电子邮箱\nExample: user@example.com",
                    "type": "string"
                },
                "nickname": {
                    "description": "用户昵称\nExample: 游戏达人",
                    "type": "string"
                },
                "personality_tags": {
                    "description": "个性标签\nExample: [\"竞技\",\"团队合作\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "phone": {
                    "description": "手机号码\nExample: 13800138000",
                    "type": "string"
                },
                "playStyle_tags": {
                    "description": "玩法偏好\nExample: [\"PVP\",\"副本\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "self_evaluatedLevel": {
                    "description": "自评等级\nExample: 高级玩家",
                    "type": "string"
                },
                "system_score": {
                    "description": "系统评分\nExample: 85",
                    "type": "integer"
                },
                "user_id": {
                    "description": "用户ID\nExample: 123456",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名\nExample: admin123",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "用户认证服务API文档",
	Description:      "用户登录认证接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
