server:
  address: "localhost:8080"
  port: 8080
  timeout: 30s
mysql:
  host: "mysql"
  port: 3306
  db: goodminton_db
  credentials:
    username: "root"
    password: "root123123"
  connmaxlifetime: 1
  maxopenconns: 100
  maxidleconns: 10
redis:
  addr: "redis:6379"
  db: 0
  poolsize: 100
  cookie_expire: 240
  like_expire: 168 #hour
hfut-api:
  host: "hfut-api"
  port: 8082
  retry: 20 #重试次数
logging:
  stdout_level: "debug"
  file_path: "/var/lib/static/log"
  file_level: "debug"
  max_size: 100 #单位MB
  max_backups: 10
  max_age: 30 #单位天
  compress: true
static:
  root_path: /var/lib/static
  avatars_path: /var/lib/static/avatars
  backimage_path: /var/lib/static/backimages
  post_path: /var/lib/static/posts
  book_path: /var/lib/static/books
auth:
  max_age: 240 #单位小时
cache:
  read_expiration: 30 #单位秒
  write_expiration: 30 #单位秒