server:
  address: "127.0.0.1:8080"
  port: 8080
  timeout: 30s
mysql:
  host: "mysql"
  port: 3306
  db: goodminton_db
  credentials:
    username: "root"
    password: "root123123"
  connmaxlifetime: 1
  maxopenconns: 100
  maxidleconns: 10
redis:
  addr: "redis:6379"
  db: 0
  poolsize: 100
  cookie_expire: 72 
hfut-api:
  host: "hfut-api"
  port: 8082
  retry: 10
logging:
  level: "info"
image:
  avatars_path: ./static/avatars
  backimage_path: ./static/backimages
  post_path: ./static/posts
auth:
  max_age: 240 #单位小时
  